### ISSUE TITLE
API key?

### ISSUE THREAD

**Issue by bfarmstrong** [SmartableAI/developer-program#1]
When I click on "retrieve subscription key" it takes me to the products page. Incorrect link? Or am I being silly?

Thanks!

**Comment by bfarmstrong** [comment]
Never mind, on the products page I had to select "free apis" and then manually type in the name 'Coronavirus API' and click the now active subscribe button. That UX process is a little obtuse and likely needs an update, but I'm good now.

**Comment by mstealth** [comment]
no encuentro la opción para  activar la suscripción

![acceso](https://user-images.githubusercontent.com/43854193/77336252-40e8b000-6cf5-11ea-95d9-1c80178660ca.png)

**Comment by SmartableAI** [comment]
Hi 
You click 'Retrieve your Subscription'.  It will take you to the 'Products' page.  Please click 'Free APIs', and follow the instructions on that page to get a new subscription.
