### ISSUE TITLE
Canada Recovered?

### ISSUE THREAD

**Issue by HarpreetGill15** [SmartableAI/developer-program#11]
Hi I was wondering how it is showing the there are 0 recovered in Canada when in fact there are more than 1,000?

**Comment by SmartableAI** [comment]
Hello
The problem is resolved.  For Canada, I'm depending on John Hopkin's data.  They do break down the recovered number into states, so I put all recovered number in  'Canada' / 'Unassigned Location'

**Comment by HarpreetGill15** [comment]
Oh okay okay thank you!
