### ISSUE TITLE
Query different country 

### ISSUE THREAD

**Issue by HashemDeveloper** [SmartableAI/developer-program#12]
Hi how can we query different country? I tried news/CHINA on postman its empty.

**Comment by insideout** [comment]
You need to use the ISO code to query countries.  For example, use CN for China. 
https://api.smartable.ai/coronavirus/news/CN
(Of course, you will also need to attach the free api key to the above request's http header)

You can play with this in our tryit experience: 
https://developer.smartable.ai/api-details#api=coronavirus&operation=news

**Comment by HashemDeveloper** [comment]
@insideout Thank you so much I have already figured out. I have signed up to get the subscription key and read the documentation. Everything works great now. Thank you.
