### ISSUE TITLE
Global news doesn't exist

### ISSUE THREAD

**Issue by ghost** [SmartableAI/developer-program#13]
Hi, I was reading the documentation about the news endpoint. **It doesn't support global as a location as mentioned in the documentation.** Even in the try out section, its not available as an option. If I am right then for now I think either it should be removed from the documentation (would be pretty useful to have it though) or it could be added as a collection of one article (maybe based on heat) from every affected country. Added to that it would useful if there could be **support for sort parameter based on** at least the **heat field**.

**Comment by SmartableAI** [comment]
Thank you for the feedback.  I have just corrected the documentation to remove the 'global' parameter for the news api.  I will think about how to support the sorting by heat.

**Comment by SmartableAI** [comment]
Global news is now added.
