### ISSUE TITLE
Thumbs can not be downloaded?

### ISSUE THREAD

**Issue by danman12345** [SmartableAI/developer-program#14]
I try to download the news images and I get:

<!DOCTYPE html>
<html>
<head>
<title>Sun Sentinel - We are currently unavailable in your region</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
<meta name="robots" content="noindex, nofollow">
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
<style>
html,
body {
  margin: 0;
  height: 100%;
  }
a {
  color: #D80000;
  }
a:hover {
  color: #761113;
  }
.trb_nh {
  width: 100%;
  background-color: #1E1E1E;
  contain: layout size style;
  position: fixed;
  top: 0;
  opacity: 1;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  z-index: 99999;
  }
.trb_nh_uw {
  height: 60px;
  position: relative;
  top: 25%;
  background-color: #1E1E1E;
  z-index: 20;
  }
.trb_nh_l {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  background: no-repeat center center;
  background-size: initial;
  width: 55%;
  height: 42px;
  color: #D80000;
  fill: #FFF;
  }
.trb_gdprW {
  display: table;
  width: 100%;
  height: 100%;
  }
.trb_gdpr {
  height: 246px;
  display: table-cell;
  vertical-align: middle;
  text-align: center;
  color: #333333;
  padding: 0 30px;
  }
.trb_gdpr_nr {
  margin: 0 auto;
  font: 400 20px/29px Georgia, 'Droid Serif', serif;
  }
.trb_ft {
  width: 100%;
  position: fixed;
  bottom: 0;
  padding: 11px 0;
  background-color: #1E1E1E;
  font: 12px Arial, sans-serif;
  color: #FFF;
  text-align: center;
  }
@media screen and (min-width: 360px) {
  .trb_nh_l {
    left: 0;
    right: 0;
    }
  .trb_gdpr_nr {
    max-width: 555px;
    }
  }
@media screen and (orientation:landscape) {
  .trb_nh_l {
    width: 33%;
    height: 36px;
    }
  .trb_gdpr_nr {
    margin: 10px auto 30px;
    max-width: 570px;
    }
  }
@media screen and (min-width: 840px) {
  .trb_nh_uw {
    height: 88px;
    }
  .trb_nh_l {
    width: 35%;
    height: 52px;
    }
  .trb_gdpr_nr {
    margin: 40px auto 0;
    font-size: 32px;
    line-height: 43px;
    max-width: 890px;
    }
  }
</style>
</head>
<body>
  <header class="trb_nh">
    <div class="trb_nh_uw">
      <svg class="trb_nh_l" viewBox="0 0 1241.33 263.023"><path d="M877.404 20.393c0 8.973 7.453 15.954 16.95 15.954 9.573 0 17.368-7.163 17.368-15.954 0-8.888-7.795-16.115-17.37-16.115-9.495 0-16.948 7.088-16.948 16.115m-732.128 83.84c.554 28.76-25.347 45.305-73.197 45.422-40.37.107-69.52-8.223-69.49-8.212L.22 98.73H12.3l9.752 26.36c9.575 4.435 23.463 11.116 46.937 11.116 18.71 0 35.5-2.987 35.33-16.415-.14-11.72-8.89-19.73-26.84-25.42L39.85 82.2C20.17 75.74 3.62 65.462 3.62 42.75 3.618 20.21 24.452-.39 75.552.005c34.632.257 55.31 6.595 55.265 6.595l2.305 39.512h-10.91l-9.955-24.51c-5.26-3.33-18.846-8.877-35.93-8.877-17.188 0-31.932 4.583-31.932 16.297 0 9.006 9.058 15.74 21.608 19.885l44.427 15.108c24.57 8.417 34.5 22.027 34.85 40.218m127.797 42.027l-50.32.044.044-9.905h-.38c-7.67 5.8-17.95 13.16-36.7 13.07-17-.08-25.43-7.55-25.36-26.4l.3-58.45-18.33-3.97.02-9.38 50.36-4.06-.59 70.04c-.03 8.2 6.87 11.79 13.97 11.64 9.2-.2 15.21-6.22 19.06-9.79l.66-53.95-19.02-4.22.03-9.37 50.36-4.18-.41 85.36 16.37 4.1-.03 9.39zm143.416.032l-50.627.097-.332-66.49c0-9.9-5.04-13.49-13.12-13.49-5.818 0-15.166 6.71-19.934 11.38l.03 55.02 19.25 3.61.455 9.86h-70.72l.144-9.7 19.39-3.77.05-67.44-21.01-4.26v-9.02l51.06-4.36v16.18l3.4-2.4c10.98-8.15 21.58-16.08 36.3-16.08 19.5 0 25.91 7.62 25.91 28.6l-.16 58.95 19.89 3.9v9.4zm135.493-42.476c.495 28.622-22.804 45.11-65.896 45.23-36.355.106-62.586-8.213-62.568-8.192l-2.134-42.52h10.88l8.775 26.266c8.61 4.4 21.128 11.028 42.268 11.028 16.85 0 31.98-2.967 31.82-16.308-.13-11.704-8-19.648-24.17-25.334l-33.87-12.12c-17.72-6.446-32.62-16.683-32.62-39.276 0-22.464 18.75-42.98 64.76-42.584C520.4.24 539.01 6.58 538.96 6.58l2.083 39.33H531.2l-8.944-24.394c-4.74-3.32-16.966-8.824-32.348-8.824-15.485 0-28.755 4.552-28.755 16.233 0 8.93 8.154 15.644 19.45 19.79l40 15.02c22.135 8.385 31.06 21.962 31.375 40.08M655.326 93.61l-67.505-.16c0 24.467 12.72 35.89 32.96 36.35 11.09.27 20.83-4.003 28.3-12.29l6.79 5.975c-8.06 11.48-24.63 25.26-49.26 24.82-27.12-.45-51.4-21.104-51.4-51 0-32.048 21.04-52.874 52.21-52.22 35.72.726 47.93 21.79 47.93 48.526m-30.8-9.73c0-20.71-8.4-31.38-17.53-31.38-9.56 0-18.81 10.14-18.81 31.22l36.35.17zm163.69 62.08l-50.62.11-.33-66.47c0-9.91-5.04-13.5-13.15-13.5-5.79 0-15.14 6.7-19.93 11.36l.05 55.05 19.27 3.6.45 9.86h-70.73l.14-9.69 19.39-3.77.05-67.44-21.02-4.26v-9.02l51.11-4.35v16.14l3.39-2.36c11-8.17 21.58-16.07 36.3-16.07 19.5 0 25.95 7.62 25.95 28.59l-.17 58.96 19.88 3.92v9.37zm75.2-13.04c-9.39 7.89-19.58 15.58-42.53 15.58-20.73 0-26.27-9.95-26.27-30.74l.35-55.34h-19.34v-8.5c14.85-5.81 29.94-20.93 42.18-43.15h7.92l.09 39.24 30.78.12v12.62l-30.78-.21-.17 57.91c0 9.31 7.86 11.2 15.328 11.2 6.014 0 12.76-2.66 18.39-6.15l4.07 7.43zm72.45 13.04H865.2v-9.37l19.788-4.02V65.22l-19.04-3.887v-9.37l50.22-4.293v85.06l19.712 3.855zm143.99 0l-50.61.11-.35-66.47c0-9.91-5.03-13.5-13.13-13.5-5.81 0-15.17 6.7-19.93 11.36l.03 55.05 19.26 3.6.47 9.86h-70.73l.16-9.69 19.38-3.77.04-67.44-21-4.26v-9.02l51.09-4.35v16.14l3.39-2.36c10.986-8.17 21.576-16.07 36.32-16.07 19.5 0 25.92 7.62 25.92 28.59l-.18 58.96 19.9 3.92v9.37zm90.25-55.41l-67.51-.16c0 24.48 12.74 35.92 32.98 36.39 11.06.26 20.82-4.01 28.28-12.31l6.8 5.99c-8.07 11.49-24.63 25.25-49.27 24.82-27.14-.46-51.39-21.1-51.39-51.01 0-32.04 21.02-52.88 52.18-52.21 35.72.74 47.94 21.78 47.94 48.51m-30.81-9.71c0-20.71-8.39-31.4-17.51-31.4-9.59 0-18.82 10.17-18.82 31.23l36.33.18zm100.72 65.13h-70.47v-9.92l19.56-4.42V16.25l-18.84-3.9V4.53l50.1-4.52v131.597l19.66 4.42z"></path><path fill-rule="evenodd" clip-rule="evenodd" fill="#fff" d="M261.895 294.756c.245-.043.245.16 0 .128v-.128z"></path><path d="M817.266 226.473c-135.293-15.57-275.91-31.952-427.448-38.645-72.85-3.223-148.584-3.887-221.278-.096-62.12 3.23-118.538 7.598-168.54 15.27v8.903c85.356-9.348 262.015-22 415.466-12.737 174.22 10.536 265.565 33.493 401.35 49.522 90.704 10.708 195.255 17.294 299.997 13.01 44.275-1.81 86.217-5.46 124.518-10.376v-33.782c-37.21 6.827-78.89 12.594-123.89 16.083-101.21 7.86-207.27 3.534-300.17-7.152zm167.925-18.707c-162.26 5.503-302.24-4.615-436.09-16.618-60.8-5.456-125.12-9.744-191.24-12.244-118.82-6.527-243.07-7.737-357.85-.557v12.502c70.26-6.96 146.31-10.84 223.67-11.18 112.61-.52 223.25 6.08 325.17 16.11 45.86 4.52 193.76 15.62 193.76 15.62 79.75 5.31 162.08 8.33 244.81 6.34 100-2.42 186.05-13.62 253.92-28.81v-18.21c-65.61 16.87-149.81 33.43-256.14 37.03z" fill="currentColor"></path>
      </svg>
    </div>
  </header>
  <div class="trb_gdprW">
    <div class="trb_gdpr">
      <div class="trb_gdpr_nr">Unfortunately, our website is currently unavailable in most European countries. We are engaged on the issue and committed to looking at options that support our full range of digital offerings to the EU market. We continue to identify technical compliance solutions that will provide all readers with our award-winning journalism.</div>
    </div>
  </div>
  <footer class="trb_ft">Copyright &#169; 2018, Sun Sentinel</footer>
</body>
</html>

**Comment by SmartableAI** [comment]
Could you please provide the title of the news?

**Comment by SmartableAI** [comment]
Hello
I haven't heard from you.  I'm temporarily closing the ticket. Please feel free to reopen it, and offer more details.
