### ISSUE TITLE
ISO code "TZ" for Tanzania gives 404 error

### ISSUE THREAD

**Issue by lividavi19** [SmartableAI/developer-program#15]
I get 404 error when passing iso code "TZ "(ISO code for Tanzania) on the ../stats endpoint.
Can it be that iso code for Tanzania is different than "TZ" in your API?
This is the case for codes of some other countries codes too, such as Kenya, Uganda, etc.

**Comment by lividavi19** [comment]
This error comes because data for the specified countries don't exist in the API, so I'm closing this issue, but already opened a new one to address the issue for nonexistence of data in the API.

**Comment by SmartableAI** [comment]
Hello
I assume you are referring to the stats api.  I have just added the countries  to the stats api.  Please try again and let me know.  

Thanks
Scott

**Comment by lividavi19** [comment]
Yeah I meant for the stats endpoint, I'll check it out, and get back with the feedback.
