### ISSUE TITLE
No Data for East African Countries

### ISSUE THREAD

**Issue by lividavi19** [SmartableAI/developer-program#17]
Looking into the CSV data file, I see that there's no data for the East African countries.
I want my project to show the data for these countries too, can you please add the data for them to the API?

The countries are;
Tanzania
Kenya
Uganda
Burundi
Rwanda
South Sudan
=> Can you please add the data for the Congo DRC(the "Kinshasha" one) as well?

Thanks in advance.

**Comment by lividavi19** [comment]
This seems to be the case for the issue #15, where querying data for TZ(for Tanzania) ISO2 code gives 404, not found error. Because the data for Tanzania is not there in the API data set.

**Comment by SmartableAI** [comment]
Hello
I have just added these countries.  The countries' ISO code may not show up in our 'tryit' experience, but you should be able to call them from the API.  Please have a try and let me know if anything is missing. 

Thanks
Scott

**Comment by lividavi19** [comment]
Sure friend, I'll check out the endpoint, and I'll let you know.

**Comment by lividavi19** [comment]
@SmartableAI 
Thanks for the update friend, now i can pull the data for the East African countries.

**Comment by lividavi19** [comment]
Closing the issue now...
