### ISSUE TITLE
Python Help!

### ISSUE THREAD

**Issue by apiedram** [SmartableAI/developer-program#3]
![Screen Shot 2020-03-20 at 10 39 43 AM](https://user-images.githubusercontent.com/57848766/77185664-62e4f700-6a97-11ea-9be1-f5e743e249f0.png)
Hi, Why I am getting these errors?

**Comment by SmartableAI** [comment]
Hello
Please try adding the following line of code above conn.request

```
conn = http.client.HTTPSConnection(""https://api.smartable.ai/coronavirus/stats/us")
```

Replace "us" in the above code with the ISO code you are querying against.

**Comment by apiedram** [comment]
![Screen Shot 2020-03-20 at 2 59 20 PM](https://user-images.githubusercontent.com/57848766/77205937-8b7ee800-6abb-11ea-9ad5-054c9569b74f.png)
![Screen Shot 2020-03-20 at 2 59 28 PM](https://user-images.githubusercontent.com/57848766/77205941-8e79d880-6abb-11ea-9616-73cfa49615d6.png)

And inside of "try:" same thing. I'm so sorry, I need to run this to help my country.

**Comment by SmartableAI** [comment]
I put a double quote in my earlier snippet.  Sorry. 

Here is a working code example.  I tested it in python 2.7.  Please replace 'subscription key' with your own key.

```python
import urllib, urllib2, json

headers = {
# Request headers
'Cache-Control': 'no-cache',
'Subscription-Key': '<put your own key here>',
}
try:
    req = urllib2.Request("https://api.smartable.ai/coronavirus/stats/CR", None, headers)
    response = urllib2.urlopen(req)
    data = response.read()
    result = json.loads(data)
    print(result["updatedDateTime"])
    print(result["stats"]["totalConfirmedCases"])

except Exception as e:
    print(e.code)
```

**Comment by apiedram** [comment]
I get it but with this code in Python 3.6

`from urllib.request import urlopen`
`import http.client, urllib.request, urllib.parse, urllib.error, base64, json, requests`

`headers = {`
`'Cache-Control': 'no-cache',`
`'Subscription-Key': 'KEY',`
`}`
`try:`
`  data = requests.get("https://api.smartable.ai/coronavirus/stats/CR", headers=headers)`
`   print(data.text)`
`except Exception as e:`
`   print(e.code)`


is working! Thank you.
