### ISSUE TITLE
French Polynesia ?

### ISSUE THREAD

**Issue by apiedram** [SmartableAI/developer-program#6]
Error in the confirmed cases for French Polynesia it says. 19,856
![Screen Shot 2020-03-23 at 7 35 37 PM](https://user-images.githubusercontent.com/57848766/77379179-a19bdb00-6d3d-11ea-8c71-be1e36f91f96.png)

i think its taking this from France:
![Screen Shot 2020-03-23 at 7 34 17 PM](https://user-images.githubusercontent.com/57848766/77379177-9f398100-6d3d-11ea-8d66-3eaad833ebcf.png)

Real for today is 18 total.

**Comment by SmartableAI** [comment]
Sorry for the error.  The problem was fixed a day ago.  We have also added additional checking to avoid this kind of mistakes in the future.
